CSharp Assignments
poojakalegithub/Smita_Repo pull request #6
Opened 2022-11-15 10:42 UTC by SmitaPradhan2299

2022-11-15 12:29 UTC, poojakalegithub requested changes
I have reviewed assignment 1 and 2, commit the changes as per comments, then you are good to merge this PR.

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment1/StringOperations.cs
> +            if (res2 == true)
can we simplify this expression?

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment1/StringOperations.cs
> +            if (res2 == true)
can we use string.compare?

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment1/StringOperations.cs
> +            Console.WriteLine("First name: " +firstName);
is there any other way to pass parameters to the console without doing {0} or +firstname?

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment1/countriesEnum.cs
> +        String res=Country.ToUpper();
variable name

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment1/EmailValidation.cs
> +    string email1 = "Smitanpradhan33@gmail.com";
email1?

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment1/EmailValidation.cs
> +            if (email1.Contains('@') == true && email1.EndsWith(".com") == true)
can we simplify this expression? Also what if the domain is different?

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment1/Person.cs
> +        public byte Age { get; set; }
why you have used byte for age?

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment1/Employee.cs
> +            public string JobTitle { get; set; }
check variable declaration standards

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment2/Student.cs
> +    class Student
what will be the default access modifier if we do specify it?

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment2/Student.cs
> +    {
indentations

2022-11-15 12:29 UTC, poojakalegithub commented on Basic_CSharp/Assignment2/Employee.cs
> +        public void sortEmp()
function name

2022-11-16 08:03 UTC, SmitaPradhan2299 commented on Basic_CSharp/Assignment1/StringOperations.cs
> +            if (res2 == true)
Yes, we can.
I have updated the code using compare method.

2022-11-16 08:08 UTC, SmitaPradhan2299 commented on Basic_CSharp/Assignment1/StringOperations.cs
> +            Console.WriteLine("First name: " +firstName);
Yes, we can insert a $ character before the string then an interpolation expression must contained inside an opening and closing brace, ({ and })

2022-11-16 08:08 UTC, SmitaPradhan2299 commented on Basic_CSharp/Assignment1/countriesEnum.cs
> +        String res=Country.ToUpper();
Updated variable name.

2022-11-16 08:09 UTC, SmitaPradhan2299 commented on Basic_CSharp/Assignment1/EmailValidation.cs
> +    string email1 = "Smitanpradhan33@gmail.com";
Updated.

2022-11-16 08:12 UTC, SmitaPradhan2299 commented on Basic_CSharp/Assignment1/Person.cs
> +        public byte Age { get; set; }
A maximum value byte can store  is +-127 and i thought that is enough to store age.

2022-11-16 08:12 UTC, SmitaPradhan2299 commented on Basic_CSharp/Assignment1/Employee.cs
> +            public string JobTitle { get; set; }
Yes

2022-11-16 08:14 UTC, SmitaPradhan2299 commented on Basic_CSharp/Assignment2/Student.cs
> +    class Student
Internal

2022-11-16 08:14 UTC, SmitaPradhan2299 commented on Basic_CSharp/Assignment2/Employee.cs
> +        public void sortEmp()
Changed the function name.

2022-11-16 08:19 UTC, SmitaPradhan2299 commented on Basic_CSharp/Assignment1/EmailValidation.cs
> +            if (email1.Contains('@') == true && email1.EndsWith(".com") == true)
Updated the code so that domain like  .com , .in and .org can also get validated

2022-11-23 09:39 UTC, poojakalegithub approved these changes

2022-11-28 03:44 UTC, merged